import React from 'react';

function Help() {
    return (
        <div className='Help'>
            <h1>Help</h1>
            <h3>
                Is the game solvable?
            </h3>
            <p>
                Yes! Though it’s relatively difficult to see at a glance whether any given board is solvable — I assure you that all the boards generated by this webapp have a solution. If you want a more in-depth explanation <a href='https://ida.mtholyoke.edu/xmlui/bitstream/handle/10166/693/375.pdf?sequence=1&isAllowed=y'><strong>here</strong></a>'s some light reading on the topic.
            </p>
            <h3>
                Can I play with a different size grid?
            </h3>
            <p>
                Yes! Simply click the 'Toggle Grid' button underneath the title of the gameboard to cycle between 3x3, 4x4, and 5x5 grids.
            </p>
            <h3>
                How do I win?
            </h3>
            <p>
                That's a good question! This is a difficult game and I am personally TERRIBLE at it! Hopefully you'll prove better at it than I am, though should you get stuck you could always <a href='http://perfectweb.org/ddo/solver/vale_puzzle.html'><strong>cheat</strong></a>!
            </p>
        </div>
    );
}

export default Help;