import React from 'react';

function Help() {
    return (
        <div className='Help'>
            <h1>Help</h1>
            <h3>
                How do I play?
            </h3>
            <p>
                You play by clicking any square on the gameboard grid. Doing so will toggle that squares and the four adjacent squares' lights to their opposite state (lights that were on will turn off, and vice versa). Once all the lights are turned off, you win!
            </p>
            <h3>
                Can I play with a different size grid?
            </h3>
            <p>
                Yes! Simply click the 'Toggle Grid' button underneath the title of the gameboard to cycle between 3x3, 4x4, and 5x5 grids.
            </p>
            <h3>
                What's the difficulty level of the various grids?
            </h3>
            <table>
                <thead>
                    <tr>
                        <th>Beginner</th>
                        <th>Intermediate</th>
                        <th>Hard</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>4x4</td>
                        <td>3x3</td>
                        <td>5x5</td>
                    </tr>
                </tbody>
            </table>
            <h3>
                Is the game solvable?
            </h3>
            <p>
                Yes! Though it’s relatively difficult to see at a glance whether any given board is solvable — I assure you that all the boards generated by the game has a solution. If you want a more in-depth look at the logic behind Lights/Out, <a href='https://ida.mtholyoke.edu/xmlui/bitstream/handle/10166/693/375.pdf?sequence=1&isAllowed=y'><strong>here</strong></a>'s some light reading on the topic.
            </p>
            <h3>
                How do I win?
            </h3>
            <p>
                That's a good question! This is a difficult game and I am personally TERRIBLE at it! I'm hopeful you'll prove better at it than I am — though should you get stuck you could always <a href='http://perfectweb.org/ddo/solver/vale_puzzle.html'><strong>cheat</strong></a>!
            </p>
        </div>
    );
}

export default Help;